### ISSUE TITLE
[!] Not a valid IP address in the text file:null

### ISSUE THREAD

**Issue by bbrendon** [TKCERT/net-consolidator#2]
following the guide here with the google IP blocks gives errors
https://webmasters.stackexchange.com/a/138323/126704

```
$ python3 net-consolidator/net-consolidator.py -f full -s subtract
[!] Not a valid IP address in the text file:null
[*] Stopping now!
```

**Comment by raspispass** [comment]
According to the referenced guide, you issued the following commands:

`curl -s https://www.gstatic.com/ipranges/goog.txt > full`
`curl -s https://www.gstatic.com/ipranges/cloud.json > subtract.json`
`jq '.prefixes[].ipv4Prefix' subtract.json > subtract.quote`
`cat subtract.quote  | sed 's/"//g' > subtract`
`git clone https://github.com/TKCERT/net-consolidator`
`python3 net-consolidator/net-consolidator.py -f full -s subtract`

The error message in your post indicates that the line including the string "null" cannot be parsed as it is not a valid IP address. I executed the commands above and found 5 lines with the string "null" in the file subtract. If you delete them the script will work.

Another message might occur for the file "full":
`[!] Not a valid IP address in the text file:2001:4860::/32`

Sadly, the script doesn't yet support ipv6 when checking for the string syntax per input line. The used library netaddr supports ipv6 so by supporting ipv6 via regex in the function getValidIpObject, the script should also work for ipv6.

**Comment by bbrendon** [comment]
I'm SOOO Sorry. The word "null" actually appears burried in that subtract file. My BAD!

**Comment by bbrendon** [comment]
Ok. I see
